# Generated by Django 2.1 on 2019-04-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
