# Generated by Django 2.1 on 2019-04-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190423_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donator_id',
            new_name='donator',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='pic',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='reporter_id',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='project_id',
            new_name='project',
        ),
    ]
