# Generated by Django 2.1 on 2019-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190423_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
