# Generated by Django 2.1 on 2019-04-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('FB', models.CharField(max_length=60)),
                ('picture', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
