# Generated by Django 2.1 on 2019-04-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190423_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FB',
            field=models.URLField(max_length=60),
        ),
    ]
