# Generated by Django 2.1 on 2019-04-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='commentreport',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentreport',
            old_name='reporter_id',
            new_name='reporter',
        ),
    ]
